export enum UserRole {
  CLIENT = 'CLIENT',
  LAWYER = 'LAWYER',
  GUEST = 'GUEST'
}

export enum CaseStatus {
  DRAFT = 'Draft',
  OPEN = 'Open for Bids',
  PENDING_ESCROW = 'Pending Escrow',
  ACTIVE = 'Active',
  COMPLETED = 'Completed'
}

export interface LawyerProfile {
  id: string;
  name: string;
  firm: string;
  rate: number;
  rating: number;
  verified: boolean;
  specialties: string[];
  bio: string;
  yearsExperience: number;
  location: string;
  education: string;
  recentWork: string[];
}

export interface Bid {
  id: string;
  lawyerId: string;
  lawyerName: string;
  amount: number;
  message: string;
  date: string;
}

export interface CaseData {
  id: string;
  title: string;
  rawDescription: string;
  aiSummary: string; // The professional brief generated by Gemini
  keyIssues: string[];
  suggestedBudgetRange: string;
  status: CaseStatus;
  bids: Bid[];
  createdAt: string;
  clientName: string;
}

export interface User {
  id: string;
  name: string;
  role: UserRole;
  balance?: number; // Simulated wallet/escrow balance
}